"use client";

import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import { Project, Analysis, Issue } from "@prisma/client";

interface ExportButtonProps {
    project: Project;
    analysis: Analysis;
    issues: Issue[];
}

export function ExportButton({ project, analysis, issues }: ExportButtonProps) {
    const handleExport = () => {
        // 1. Generate Markdown Content
        const timestamp = new Date().toLocaleString();
        const score = analysis.score ?? 0;

        // Group issues by category
        const critical = issues.filter(i => i.severity === "CRITICAL").length;
        const high = issues.filter(i => i.severity === "HIGH").length;
        const medium = issues.filter(i => i.severity === "MEDIUM").length;
        const low = issues.filter(i => i.severity === "LOW").length;

        let md = `# AI Code Review Report\n\n`;
        md += `**Project:** ${project.owner}/${project.repo}\n`;
        md += `**Date:** ${timestamp}\n`;
        md += `**Health Score:** ${score}/100\n\n`;

        md += `## Executive Summary\n`;
        md += `- **Critical Issues:** ${critical}\n`;
        md += `- **High Severity:** ${high}\n`;
        md += `- **Medium Severity:** ${medium}\n`;
        md += `- **Low Severity:** ${low}\n`;
        md += `- **Total Issues:** ${issues.length}\n\n`;

        md += `## Detailed Issues\n\n`;
        issues.forEach((issue, index) => {
            md += `### ${index + 1}. [${issue.severity}] ${issue.category} in \`${issue.filePath}\`\n`;
            md += `**Line:** ${issue.lineNumber}\n\n`;
            md += `> ${issue.message}\n\n`;

            if (issue.code) {
                md += "```javascript\n" + issue.code + "\n```\n\n";
            }
        });

        md += `\n---\n*Generated by AI Code Review Platform*`;

        // 2. Trigger Download
        const blob = new Blob([md], { type: "text/markdown" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `report-${project.repo}-${analysis.id}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <Button variant="outline" size="sm" onClick={handleExport}>
            <Download className="mr-2 h-4 w-4" />
            Export Report
        </Button>
    );
}
